/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package guis;


import Database.Database;
import java.io.File;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static java.nio.file.StandardCopyOption.*;
import java.sql.Connection;
import java.sql.Statement;
/**
 *
 * @author GC
 */
public class NewScenario extends javax.swing.JDialog {
    public boolean done = false;
    public final static String[] title = {"Tạo kịch bản mới", "Đổi tên kịch bản", "Sao chép kịch bản"};
    public final static String[] text = {"Tạo", "Đổi", "Tạo bản sao"};
    public final static int CREATE = 0;
    public final static int RENAME = 1;
    public final static int COPY = 2;
    
    private int option;
    private String dbName;
    /**
     * Creates new form NewScenario
     */
    public NewScenario(int option, String dbName) {
        setModal(true);
        this.option = option;
        this.dbName = dbName;
        try {          
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            initComponents();
            this.setTitle(title[option]);
            jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, title[option], javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12)));
            bt_Ok.setText(text[option]);
            tf_Name.setText(dbName);
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            Logger.getLogger(NewScenario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            Logger.getLogger(NewScenario.class.getName()).log(Level.SEVERE, null, ex);
        } catch (UnsupportedLookAndFeelException ex) {
            Logger.getLogger(NewScenario.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tf_Name = new javax.swing.JTextField();
        bt_Ok = new javax.swing.JButton();
        bt_Cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tạo kịch bản mới");

        jPanel1.setBackground(javax.swing.UIManager.getDefaults().getColor("EditorPane.selectionBackground"));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Tạo kịch bản mới", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Tên kịch bản:");

        bt_Ok.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/oksmall.png"))); // NOI18N
        bt_Ok.setText("Tạo");
        bt_Ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_OkActionPerformed(evt);
            }
        });

        bt_Cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cancelsmall.png"))); // NOI18N
        bt_Cancel.setText("Hủy");
        bt_Cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_CancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tf_Name))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 142, Short.MAX_VALUE)
                        .addComponent(bt_Ok, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bt_Cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt_Cancel)
                    .addComponent(bt_Ok))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt_CancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_CancelActionPerformed
        dispose();
    }//GEN-LAST:event_bt_CancelActionPerformed

    private void bt_OkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_OkActionPerformed
        if(tf_Name.getText().equals("")) JOptionPane.showMessageDialog(null, "Chưa nhập tên kịch bản");
        else{
        switch(option){
            case CREATE:{
                File newDb = new File("scenarioDB\\" + tf_Name.getText() + ".db");
                if(newDb.exists()){
                    JOptionPane.showMessageDialog(null, "Hãy sử dụng tên khác");
                    return;
                }else{
                    try{
                        newDb.createNewFile();
                        Connection con = Database.Open(tf_Name.getText());
                        Statement stm = con.createStatement();
                        Database.createAll(stm);
                        done = true;
                        stm.close();
                        con.close();
                    }catch(Exception e){
                        JOptionPane.showMessageDialog(null,"Error: " + e.getMessage());
                    }
                }
                dispose();
            }
                break;
            case RENAME:{
                try{
                    File oldDb = new File("scenarioDB\\" + dbName + ".db");
                    oldDb.renameTo(new File("scenarioDB\\" + tf_Name.getText() + ".db"));
                    done = true;
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Error: " + e.getMessage());
                    return;
                }
                dispose();
            }
                break;
            case COPY:{
                //File oldDb = new File("scenarioDB\\" + dbName + ".db");
                File newDb = new File("scenarioDB\\" + tf_Name.getText() + ".db");
                while(newDb.exists()){
                    JOptionPane.showMessageDialog(null, "Hãy sử dụng tên khác");
                    return;
                }
                try{
                    Path destination = Paths.get("scenarioDB\\" + tf_Name.getText() + ".db");
                    Path source = Paths.get("scenarioDB\\" + dbName + ".db");
                    Files.copy(source, destination, REPLACE_EXISTING);
                    done = true;
                }catch(Exception e){
                    JOptionPane.showMessageDialog(null,"Error: " + e.getMessage());
                }
                dispose();
            }
                break;
            default: dispose();
        }
        }
    }//GEN-LAST:event_bt_OkActionPerformed

    
//public static void checkTypeDatabase(){
//    File newDb = new File("scenarioDB\\TypeDatabase.db");
//        if(!newDb.exists()){
//            try {
//                newDb.createNewFile();
//                Connection con = Database.Open("TypeDatabase");
//                Statement stm = con.createStatement();
//                Database.createHostTypeTable(stm);
//                Database.createVmTypeTable(stm);
//                stm.close();
//                con.close();
//                } catch (Exception e) {
//                    Logger.getLogger(NewScenario.class.getName()).log(Level.SEVERE, null, e);
//            }
//        }
//}    

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(NewScenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(NewScenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(NewScenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(NewScenario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the dialog */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                NewScenario dialog = new NewScenario(new javax.swing.JFrame(), true);
//                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
//                    @Override
//                    public void windowClosing(java.awt.event.WindowEvent e) {
//                        System.exit(0);
//                    }
//                });
//                dialog.setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt_Cancel;
    private javax.swing.JButton bt_Ok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField tf_Name;
    // End of variables declaration//GEN-END:variables
}
